### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nextRowKey' of undefined 

### ISSUE THREAD

**Issue by ahmetb** [jeffwilcox/azure-table-explorer#1]
I am getting this JS error on console  after clicking on some of my tables.

```
Uncaught TypeError: Cannot read property 'nextRowKey' of undefined 
```

I'm not sure if it is related to pagination but I get this in so many tables. Response comes from server with HTTP 200 but there's something wrong at client side.

One table containing only 1 row with PK, RK, TS (default cols) and a bool field (IsActive). If you need a repro, please let me know. Thanks.

**Comment by ahmetb** [comment]
fixed in #2.

**Comment by jeffwilcox** [comment]
First PR, thanks!

p.s. This was never designed to actually be useful :)

**Comment by ahmetb** [comment]
there are similar hosted apps out there, I needed to use this for a sensitive internal Azure account. this is the only one developed by an employee and hosted on https by you. I might add support for viewing `binary` columns soon.

**Comment by ahmetb** [comment]
In fact it already handles `binary` types fairly good. Can you please deploy latest to https://waztable.azurewebsites.net/ when you have time? We'll be using it in our team, thanks!
